# Generated by Django 2.1.5 on 2019-01-26 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('person', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personreplaycomment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personreplaycomment',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='comment.PersonComment'),
        ),
        migrations.AddField(
            model_name='personcomment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personcomment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='person.Person'),
        ),
        migrations.AddField(
            model_name='itemreplaycomment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemreplaycomment',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='comment.ItemComment'),
        ),
        migrations.AddField(
            model_name='itemcomment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcomment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='item.Item'),
        ),
    ]
